### ISSUE TITLE
[design/frontend-68/main/headerfooter] 페이지 공용 header,footer 디자인

### ISSUE THREAD

**Issue by GTU9** [DoYous/Senials-Frontend#68]
## 어떤 기능인가요?

> 페이지 공용 header,footer 디자인

## 작업 상세 내용

- [x] 공용 header JSX, CSS 작성
- [x] 공용 footer JSX, CSS 작성

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implemented a common header and footer in the Layout component. The header includes navigation links, and the footer contains copyright information. Styles are added to match the existing design.

You can review changes in this commit: https://github.com/lkilu6456546/DoYous-Senials-Frontend-68/commit/ad1c86bb53b9e825c26bded986e5d989f4e8fd67.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
